### ISSUE TITLE
Quicker way to block comments than Rightclick?

### ISSUE THREAD

**Issue by Ezelmannen** [jscher2000/De-Troll-YouTube---Hide-Unwanted-Commenters#3]
As said before, I love the idea of this Add-on, but it is a bit cumbersome to use when you want to block a lot of commenters.
Is there a possibility for you to add a quicker way to block commenters? Perhaps by adding a Red X after the usersname one can click in the render of the page. Or maybe holding ctrl+leftclick on a username blocks it?

**Comment by jscher2000** [comment]
I created a version 0.6 that inserts a little trash can button next to each commenter name. Only tested lightly, but seems to work. Let me know if you discover any glitches.

**Comment by Ezelmannen** [comment]
Thanks for updating so quickly!
But unfortunately it didn't work over here. :-/

I've updated the Add-on, Stopped all other Add-ons, Restarted Firefox, and end up with this:
![image](https://user-images.githubusercontent.com/28021692/104135170-9ed2ab00-538e-11eb-822e-b137c9a49c3a.png)
It seems like it inserts a lot of buttons, but no icon perhaps?

I did a "show selection source" of the affected parts. I hope that can help troubleshoot it:
```<div id="header-author" class="style-scope ytd-comment-renderer">
        <a id="author-text" class="yt-simple-endpoint style-scope ytd-comment-renderer" href="/channel/UCvAKSZj_4veP6V--pSoP61A">
          <span class="style-scope ytd-comment-renderer">
            OmegaVideoGameGod
          </span>
        </a>
        <button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><button></button><span id="author-comment-badge" class="style-scope ytd-comment-renderer" hidden=""></span>
        <span id="sponsor-comment-badge" class="style-scope ytd-comment-renderer" hidden=""></span>
        
        <yt-formatted-string class="published-time-text above-comment style-scope ytd-comment-renderer" has-link-only_=""><a class="yt-simple-endpoint style-scope yt-formatted-string" spellcheck="false" href="/watch?v=ajVqrIu6aG8&amp;lc=Ugz-o4jT_c2mPaJErLN4AaABAg" dir="auto">9 hours ago</a></yt-formatted-string>
        <span id="author-reputation" class="style-scope ytd-comment-renderer"></span>
        <span id="sponsors-only-badge" class="style-scope ytd-comment-renderer" hidden=""></span>

        <span id="moderation-reason-divider" class="style-scope ytd-comment-renderer" hidden="">
          •
        </span>
        <span id="moderation-reason-text" class="style-scope ytd-comment-renderer" hidden="">
          
        </span>
      </div>```

**Comment by jscher2000** [comment]
The details of the button template are defined here:

https://github.com/jscher2000/De-Troll-YouTube---Hide-Unwanted-Commenters/blob/master/de-troll-content.js#L132

For some reason, that is getting skipped or failing on yours, but I couldn't tell you why, It's probably easier for me to move lines 134-137 up to line 106. 

Could you test unchecking and re-checking the box on the Options tab for the extension to see whether that helps at all?

**Comment by jscher2000** [comment]
Okay, hopefully version 0.6.1 has fixed it.

**Comment by Ezelmannen** [comment]
Now it works. Great!
Though, I've noticed the Trashcan renders on the left side of the Username sometimes and there is a check mark on the right side.
It seems to be rare though, only seen it twice on the video I scrolled through now:
![image](https://user-images.githubusercontent.com/28021692/104138547-04319680-53a5-11eb-96d9-f6ff42bd792a.png)
Still, it seems to work. :-)

**Comment by jscher2000** [comment]
I noticed left side when the channel name shows instead of the author name. Not sure if there are other times that it happens. I wonder what the checkmark means? (I hardly use YouTube in a browser, mostly in the mobile app.)

_Edit:_ For Verified users, Google hides the first author name and shows a special tag. So I need to move the trash can in that case.
